services:
  clean-architecture.api:
    image: ${DOCKER_REGISTRY-}cleanarchitecture
    container_name: CleanArchitecture.Api
    build:
      context: .
      dockerfile: src/Web.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - '7070:8080'
      - '7071:8081'
    depends_on:
      - clean-architecture.database

  clean-architecture.database:
    image: postgres:latest
    container_name: CleanArchitecture.Database
    environment:
      - POSTGRES_DB=clean_arch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
        
  clean-architecture.seq:
    image: datalust/seq:latest
    container_name: CleanArchitecture.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
        
  clean-architecture.redis:
    image: redis:latest
    container_name: CleanArchitecture.Redis
    restart: always
    ports:
      - '6379:6379'